### ISSUE TITLE
Installable with Cask

### ISSUE THREAD

**Issue by stjohnjohnson** [ekreutz/CornerCal#2]
This is a great application.  Thank you so much.

Was wondering if you thought of supporting installing this via homebrew cask?

**Comment by ekreutz** [comment]
I'll probably add some better means of installing at some point, yes!
Let's see if that's cask or something else.

**Comment by ekreutz** [comment]
I thought of eg. https://sparkle-project.org and perhaps a dmg that would live in the repo: https://github.com/LinusU/node-appdmg

**Comment by nalexander50** [comment]
+1 for Cask!

The Sparkle framework is great and will help with auto-updates. Another low-tech solution is just to leverage GitHub Releases and upload a zip containing your .app. I think that would also be sufficient for using Cask.

**Comment by brunoxd13** [comment]
+1 for Cask!

I also support that the homebrew cask should be used.

Thanks a lot, it's fantastic :)

**Comment by vitorgalvao** [comment]
CornerCal is [now included in Homebrew Cask](https://github.com/Homebrew/homebrew-cask/pull/70091), thanks to @stjohnjohnson.
