### ISSUE TITLE
Why not have a Exit interface.

### ISSUE THREAD

**Issue by windorz9** [ekreutz/CornerCal#4]
This is a great application. Thank you so much.
But I am so sad, I can't see a exit. But I really  like this application.

**Comment by ekreutz** [comment]
That's a great idea. There are some usability features in this app that aren't really there yet. I'll take note and add it soon!

**Comment by ekreutz** [comment]
Also, I guess this isn't an app you really want to quit a lot. It should always be on if you use it.. :D

**Comment by windorz9** [comment]
ok, you are right, so you need to add a automatically launch app on login. I think that is good. 👍 :D.

**Comment by robert-corlett** [comment]
Just a quick amateur tip for other amateurs. 
For anyone wanting to add this themselves but are unfamiliar with xcode (like me), it is a breeze:

Open the project in xcode. 
Select "ManMenu.xib" in the sidebar to see the main menu UI editor. 
Click the + button in the top right of the window and search for 'menu item'. 
Drag it to the menu in the UI editor. 
Name it Quit or whatever you prefer. 
Open MainMenuController.swift in the right-hand editor (file➞new➞editor if you dont see one) then paste the following new function in:

    @IBAction func quitClicked(_ sender: NSMenuItem) {
        NSApp.terminate(self);
    }

Then right click on your new menu button, drag the handle from 'sent actions' to the function that you just pasted into the editor.
Boom! You are done. Click Project ➞ Build and it will build the app.
